version: "3.9"

services:
    pgdb:
        image: postgres:16.1
        container_name: pgdb
        env_file: ./backend/.envs/.env.postgres
        ports:
            - "5432:5432"
        volumes:
            - ./data:/var/lib/postgresql/data

    backend:
        build:
            context: backend
            dockerfile: docker/dev.Dockerfile
        container_name: backend
        command: ./scripts/start-dev.sh
        volumes:
            - ./backend:/usr/src/app
        ports:
            - "8000:8000"
        env_file:
        - ./backend/.envs/.env.fastapi
        depends_on:
            - pgdb